name: GCP authorization check

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    name: Build Production Job
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: auth_to_gcp
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '//iam.googleapis.com/projects/817921738258/locations/global/workloadIdentityPools/rbc-github-pool/providers/rbc-github-action-provider'
          service_account: 'prod-pd-library-vm@prod-pd-library.iam.gserviceaccount.com'